name: accounting_app
description: A simple offline accounting app.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  flutter_slidable: ^2.0.0
  intl: ^0.18.1
  charts_flutter: ^0.14.0  # 使用确认可用的版本
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
    
