name: accounting_app
description: 中文记账应用
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 国际化核心依赖
    sdk: flutter
  intl: ^0.19.0          # 与 flutter_localizations 兼容的版本（关键修改）
  provider: ^6.0.5       # 状态管理
  sqflite: ^2.3.0        # 本地数据库
  path: ^1.8.3           # 路径处理
  flutter_slidable: ^2.0.0 # 侧滑组件
  material_design_icons_flutter: ^7.0.7296 # 图标

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true # 启用国际化代码生成
